### ISSUE TITLE
Add DCO check, maintainers file, contributing.md

### ISSUE THREAD

**Issue by thaJeztah** [docker/infrakit#196]
noticed some PRs were merged without a sign-off, and there's no contributing.md or maintainers file present in this repository. Some boilerplating can be found here https://github.com/docker/opensource/tree/master/project-template

**Comment by wfarner** [comment]
Thanks for pointing this out!  We'll hold on accepting PRs until we have this in place.

**Comment by thaJeztah** [comment]
I opened https://github.com/docker/infrakit/issues/209 to add the necessary information; PR's can be merged if they contain a proper DCO sign-off (but having the check automated would probably make it easier)

**Comment by wfarner** [comment]
Looks like we're all set here - the automated check should be configured.  Thanks again for the PR @thaJeztah!

**Comment by thaJeztah** [comment]
Great!
