### ISSUE TITLE
make -k infrakit complaining about kardianos/govendor even if installed already

### ISSUE THREAD

**Issue by goginoida** [docker/infrakit#198]
Following the README on the project page, I did a go get for "kardianos/govendor" and "golang/lint/golint".
After doing that when I am running "make -k infrakit", I am getting the below error:
`Makefile:88: *** Please install govendor: go get github.com/kardianos/govendor.  Stop.`

Also, doing "make ci" throws the error:
`Makefile:42: *** Please install golint: go get -u github.com/golang/lint/golint.  Stop.`

Go version: go-1.7.1
OS: macOS 10.12

Kindly look into this problem or suggest if I am missing something.

--
Thanks,
Gaurav

**Comment by chungers** [comment]
Did you set both the `GOPATH` and `PATH`?   Let's say your workspace directory is at `~/go`, then your repo clone should be at `~/go/src/github.com/docker/infrakit`.   Please set the environment variables:

```
export GOPATH=~/go
export PATH=$GOPATH/bin:$PATH
```
`govendor` and `golint` are installed in the `bin` directory under your $GOPATH so make sure you have the PATH environment variable set.   The Makefile just does a `which` to see if they are there.

Hope this helps.
David

**Comment by goginoida** [comment]
The PATH was not correctly set. Thanks for the pointer. Closing this thread.
