### ISSUE TITLE
./example/flavor/swarm needs documenting

### ISSUE THREAD

**Issue by mnp** [docker/infrakit#204]
A README in the style of the tutorial would be very nice.

Extra points for tying it into the Terraform example, showing how to deploy a swarm onto some terraformed instances.

**Comment by linsun** [comment]
Do we have a sample group.json file somewhere?  I'd like to try this.

**Comment by wfarner** [comment]
@linsun not yet, but i should have one today or tomorrow as i'm about to start some work on this integration.  Stay tuned!

**Comment by linsun** [comment]
@wfarner Great, thank you!  keep me posted :)

**Comment by linsun** [comment]
@wfarner any update on this...?  I tried to use it today, could not get it working.  It seems it is expecting LogicalIDs within Allocation blob, and the LogicalID needs to be the IP of the swarm master?  Seems the size isn't supported within Allocation blob when using flavor-swarm...   It is also not clear how to specify both type=manager & type=worker within the flavor-swarm blob.  Could you advise?

**Comment by wfarner** [comment]
@linsun i've added an example with PR #249.  I suspect the main source of confusion was that two groups are really needed for a Swarm (a manager group and a worker group).  At any rate, feel free to try it out and comment on the PR if more detail would be helpful.

Heads up though - i had trouble getting the worker node to join with the Swarm flavor plugin code on master.  Be sure to build from my PR when you try it out!
