### ISSUE TITLE
Add documentation for implementing a new plugin

### ISSUE THREAD

**Issue by mvaude** [docker/infrakit#207]
I am currently at the `infrakit` BoF in Berlin, I am playing around with it for the first time.
I want to create a flavor plugin for a specific stack. I cannot find anywhere documentation for when you are writing a plugin.
I am checking the source code from other flavors trying to miss nothing for my implementation.

It could be great to document a plugin implementation documentation for (future) contributors (with the requirements for a `group` or `instance` or `flavor` plugin).

**Comment by linsun** [comment]
I second this req :)

**Comment by hekaldama** [comment]
Maybe even adding a lib that people could include to get going. Similar to https://github.com/docker/go-plugins-helpers

**Comment by wfarner** [comment]
@hekaldama we have similar libraries for each plugin type, adapting the Go interfaces to HTTP servers.  Check it out! https://github.com/docker/infrakit/tree/master/spi/http

**Comment by hekaldama** [comment]
Nice!
