### ISSUE TITLE
`infrakit group watch` hangs when no arguments are provided

### ISSUE THREAD

**Issue by wfarner** [docker/infrakit#217]
This command hangs, which is confusing:
```console
$ build/infrakit group watch
```

I suspect this is an artifact of accepting input via stdin.  Perhaps we should eliminate support for configurations via stdin, or do so only by a non-default use of the command.

**Comment by chungers** [comment]
It is due to waiting on stdin for input.  The code waits for input if no positional arg is provided for file to read.  

The doc should be more clear about this behavior.  I will add a flag to turn on stdin instead

**Comment by wfarner** [comment]
Echoing my thought posed above - is there sufficient justification for keeping the behavior?  I can't imagine shell pipelines being used for this, so it's not clear what use cases we're after by taking a config from stdin.

**Comment by hekaldama** [comment]
A good question may be, "Why was it there in the first place? What problem was it solving?"

**Comment by wfarner** [comment]
Spoke with @chungers offline and it sounds like there was no strong motivation to read from stdin, so it's best to remove the behavior.
