### ISSUE TITLE
Vanilla plugin: rename fields to match instance.Spec

### ISSUE THREAD

**Issue by wfarner** [docker/infrakit#223]
The Vanilla plugin maps its `UserData` field into `instance.Spec.Init`, and `Labels` to `instance.spec.Tags`.  These fields should use the same names for consistency.

**Comment by hekaldama** [comment]
Which way should they go? E.g. UserData:Init -> Init:Init and Labels:Tags -> Tags:Tags

**Comment by wfarner** [comment]
Heh, yeah - i could have been more direct.  I suggest we standardize on the `instance.Spec` fields (`Init`, `Tags`).
