### ISSUE TITLE
rename the binaries

### ISSUE THREAD

**Issue by justincormack** [docker/infrakit#231]
Currently the binaries built by infrakit have unhelpful names, eg `cli`, `file` (conflicts with common unix command), `vagrant` (its not `vagrant`) etc. The simplest solution is to just prefix them all `infrakit-...` not sure about other options.

For the plugins maybe it doesn't matter, but then we should remove the `make install` from the Makefile.

**Comment by wfarner** [comment]
Are you on the latest master?  The binaries have been renamed, e.g `cli` to `infrakit`, `vagrant` to `infrakit-instance-vagrant`.

Great minds think alike :-)

**Comment by justincormack** [comment]
Ah cool, great, will make sure I am updated...
