### ISSUE TITLE
Updater/SPI: add support for draining instances

### ISSUE THREAD

**Issue by wfarner** [docker/infrakit#235]
Addresses this TODO in `rollingupdate.go`:
> // TODO(wfarner): Provide a mechanism to gracefully drain instances.

Draining would be a nice addition to make updates more graceful.  Command line tooling would also be nice to perform manual service drains.

**Comment by chungers** [comment]
What entity should do the drain?   "Draining" seems to be application / context dependent.  Is Flavor responsible?   Instance plugin should be pretty dumb and it doesn't feel like it should know about draining.

**Comment by wfarner** [comment]
Yeah, this seems to mean a new API call to the Flavor.

**Comment by gesellix** [comment]
How would one know whether the draining has been completed? Is there any kind of status check on group level?

**Comment by wfarner** [comment]
@gesellix good question.  Draining should be a best-effort operation, so my inclination is to make the RPC synchronous and assume completion upon a successful reply.

**Comment by gesellix** [comment]
@wfarner sounds good - I'm now asking myself how to handle "very long draining", but that's certainly an edge case and probably not in the responsibility of InfraKit.

**Comment by wfarner** [comment]
That use case was in the back of my mind, but yeah - definitely not something the approach above optimizes for.  We might still be able to accommodate it in the not-too-distant future, though, perhaps with a configuration parameter on the group to retry draining until positive acknowledgement.
