### ISSUE TITLE
Build binaries in a docker container

### ISSUE THREAD

**Issue by chungers** [docker/infrakit#238]
Some users have come across issues when building infrakit.  We can improve the build UX by doing the build inside docker containers.

Some things to consider... 
  + Support cross compilation.  Linux is the default target when building but the user's local dev platform is likely not Linux, so
  + Support GOOS=darwin or whatever the user's local development platform is.  This is necessary since we don't require docker to be runtime.

This gets into the topic of whether we should provide Docker containers to simplify experimentation and running of the binaries.  It's outside the scope of this Issue unless people feel otherwise.  Please comment here.

**Comment by justincormack** [comment]
I did make a container for build (non cross) and happy to contribute one as an example. Apart from the cross build issue, it is a bit annoying to use as you don't vendor your dependencies into the repo which means the `Dockerfile` looks like:
```
...
COPY . ./
RUN govendor sync
RUN make
```

Which makes it painfully slow to use for development as you have to re-sync each time you edit the source. I am currently vendoring infrakit and its dependencies so it is more usable for building in a container.

**Comment by wfarner** [comment]
> it is a bit annoying to use as you don't vendor your dependencies into the repo 

We've gone back and forth on this...i really like the idea of not checking in vendored sources, but it's starting to look impractical.

**Comment by thaJeztah** [comment]
SwarmKit recently switched to https://github.com/LK4D4/vndr you could check with them how that worked out so far

**Comment by wfarner** [comment]
Relevant: #189

**Comment by chungers** [comment]
I think I have a solution for the build in container / vendor / pain in the sync/ issue.   

Basically I’ve separated out the code compilation and vendor sync into two separate steps.  The vendor sync step is done in a container named by the hash of the `vendor/vendor.json`.  

The compilation of infrakit code is in a separate container but uses the first container as the data volume (via the `—volumes-from` option in docker run).   So the compiler sees the vendored code, and there's no need to do any more vendor sync unless the `vendor/vendor.json` file is updated -- at which time a new hash will produce a new data container / data volume.  This will be reused across multiple compiles as long as the the hash doesn't change.

See https://github.com/docker/infrakit/pull/241
