### ISSUE TITLE
after make binaries my terraform binary is replaced in $GOPATH/bin

### ISSUE THREAD

**Issue by linsun** [docker/infrakit#270]
After make binaries my terraform binary in $GOPATH/bin is replaced with the terraform instance plugin with the binary name terraform.  I had to manually copy the terraform binary I downloaded to the $GOPATH/bin dir so that terraform can function.

**Comment by wfarner** [comment]
I thought we resolved the name clash in #212.  Am i understanding correctly that something is still named `terraform`?

**Comment by linsun** [comment]
yes, this was fixed 2 or 3 weeks earlier when I first mentioned in #212, however, i noticed the old behavior is back since a few days ago.

**Comment by wfarner** [comment]
Have you had any luck tracking down where it's coming from?  Looking at `make binaries`, i don't see anything written with the name `terraform`, and furthermore all binaries go to `build/` rather than `$GOPATH/bin`.

**Comment by linsun** [comment]
sorry been busy all day today, may have sometime look at this tmr or friday.

**Comment by linsun** [comment]
@wfarner I tried to recreate this today but could not.  The terraform binary in the $gopath/bin dir didn't get changed.   We can close this now.

**Comment by wfarner** [comment]
Thanks for confirming, closed.

**Comment by M3kH** [comment]
I think we can open back, I get the same for Vagrant, after installing and build.
```
$> which Vagrant
/Users/-/go/bin/vagrant
```

**Comment by chungers** [comment]
The vagrant plugin binary is called `infrakit-instance-vagrant`.  There's nothing in the build that will replace the vagrant binary in your gopath.  Also we don't include the vagrant binary.
