### ISSUE TITLE
does group unwatch still work?

### ISSUE THREAD

**Issue by linsun** [docker/infrakit#271]
Group unwatch cmd was working for me, but it stops lately after pulling in changes last week or the week before.  It is either I used the wrong param (which looks right to me) or the cmd stops working.

2016-11-01 15:26:42 ☆  |2.2.4||ruby-2.3.0| linsun in ~/go/src/github.com/docker/infrakit
± |master U:8 ?:5 ✗| → build/infrakit group watch example/instance/terraform/sl-swarm-node/group.json 
watching terraform_demo_swarm_node_sl

 2016-11-01 16:02:31 ☆  |2.2.4||ruby-2.3.0| linsun in ~/go/src/github.com/docker/infrakit
± |master U:8 ?:5 ✗| → **build/infrakit group unwatch terraform_demo_swarm_node_sl**
Usage:
  build/infrakit group unwatch <group ID> [flags]

Global Flags:
      --log int       Logging level. 0 is least verbose. Max is 5 (default 4)
      --name string   Name of plugin (default "group")

**Comment by linsun** [comment]
BTW, no output from group plugin was helpful:

 2016-11-01 15:33:59 ☆  |2.2.4||ruby-2.3.0| linsun in ~/go/src/github.com/docker/infrakit
± |master U:8 ?:5 ✗| → build/infrakit-group-default 
INFO[0000] Listening at: /Users/linsun/.infrakit/plugins/group 
INFO[0034] Watching group 'terraform_demo_swarm_node_sl' 
INFO[0274] Adding 2 instances to group to reach desired 2 
INFO[0274] Created instance instance-1478030574 with tags map[infrakit.config_sha:_1iSR2SfYys4JNpQzjAmU0gKLiM= infrakit.group:terraform_demo_swarm_node_sl swarm-association-id:tSqiVoh5 swarm-id:ctyla6ovjkwnwf5z4ospftqrg] 
INFO[0275] Created instance instance-1478030575 with tags map[infrakit.group:terraform_demo_swarm_node_sl swarm-association-id:iTGxgHef swarm-id:ctyla6ovjkwnwf5z4ospftqrg infrakit.config_sha:_1iSR2SfYys4JNpQzjAmU0gKLiM=]

**Comment by wfarner** [comment]
I recently noticed this too, thanks for filing.
