### ISSUE TITLE
Combine 'watch' and 'update' group actions

### ISSUE THREAD

**Issue by wfarner** [docker/infrakit#292]
In the trend of declarative state and idempotent actions, `watch` and `update` are currently outliers.  Successfully choosing which one to invoke requires knowledge of the state of the cluster.  There should be little adverse impact to combining them, essentially treating every `watch` as an `update` (which could begin from a blank state) will make InfraKit easier to use by humans and automation.

I propose we call the new verb `commit`  meaning the following commands:

```shell
$ infrakit group watch group.json
$ infrakit group update group.json
```

would combine into
```shell
$ infrakit group commit group.json
```

The implication being that `commit` is an idempotent operation that does not depend on the current state of the cluster.

Additionally, i propose we replace the command:
```shell
$ infrakit group update-describe group.json
```
with
```shell
$ infrakit group commit group.json --pretend
```

**Comment by chungers** [comment]
Is Commit idempotent?

**Comment by wfarner** [comment]
We currently also have `infrakit group stop-update`.  I propose we approximate this behavior with `infrakit group unwatch`, which has similar behavior.  `unwatch` may even be a better practice for the stopped-update case, as it makes it more clear that the group has been put into an unclear state.

Additionally i propose we rename `unwatch` as it no longer has an inverse.  I'm proposing `ignore`.

**Comment by chungers** [comment]
My only thing with `ignore` is that it has a negative connotation, like when I ignore something bad will happen.  How about `free` or `release`?

**Comment by wfarner** [comment]
@chungers yeah, i'm not settled yet on `ignore`.  Personally, i'm less concerned with a negative connotation than i am with words that inaccurately imply behavior.  `free` is okay, but seems awkward and incomplete without a symmetrical counterpart like `malloc`.  `release` doesn't have this problem, but for some reason isn't clicking with me.

**Comment by chungers** [comment]
I suppose `release` could mean 'releasing` from management/monitoring/babysitting...

`detach` and `disconnect` also have symmetric counterpart that aren't in this mix.  `drop` feels like something left behind -- on par with `ignore`.

**Comment by wfarner** [comment]
Of the options so far i like `release` the most.  Doesn't have the same 'delete' connotation as `drop`.

**Comment by wfarner** [comment]
@chungers i'm realizing now that `release` poses confusion with the concept of 'releasing software', as in 'deploying'.  We should reconsider before landing the attached PR.

**Comment by chungers** [comment]
Good point.  Maybe just 'umanaged' or 'unsupervised'?  Not a verb though.

**Comment by wfarner** [comment]
To make progress, i'm going to proceed with `free` in the PR.  We can revisit if this feels weird later on.
