### ISSUE TITLE
Implement Engine install and configuration task after machine is created.

### ISSUE THREAD

**Issue by chungers** [docker/infrakit#30]
We need to implement a consistent way to install the Engine on a host after it's been created.  This is the last stage of the processing pipeline that looks like:

  1. Use existing or generate new SSH key for a node
  2. Create the node using provisioner API and a specified template with optionally provided overrides
  3. Install and configure Docker engine on that host 
      + Using the login credentials from 1.
      + Possibly different Engine configurations optimized for each platform node / OS version
  4. The Engine is now `ready` and can be added to a Swarm cluster (TBD later)

Note
  + We will likely not write new Engine installation scripts.  Just invoke the existing Docker installation scripts ==> will look at how Machine does this.
  + We can use the same template pattern for engine configurations: e.g. `engine_ubuntu14_04` or `engine_alpine`
  + The engine configuration template can be grouped / bundled along with the machine templates so that we have proper association of recommended engine configuration with any Edition-specific params like AMI / image id, OS version, instance types.  ==> does this mean we should group configuration templates in folders or via some naming convention of the file names?

**Comment by wfarner** [comment]
Closing this as InfraKit has evolved quite a bit since the issue was opened.  We have basic support for installing Docker Engine in the swarm Flavor plugin, though it may evolve into a separate Docker Flavor plugin.
