### ISSUE TITLE
Group-Default plugin --pretend bug

### ISSUE THREAD

**Issue by thebsdbox** [docker/infrakit#315]
When using the `--pretend` flag to examine the possible outcome of a commit, a second `--pretend` will result in the group-default plugin becoming inconsistent and requiring a restart. 

```
$ ./infrakit group commit oneview.json --pretend
Committing oneview would involve: Managing 4 instances
$ ./infrakit group commit oneview.json --pretend
Committing oneview would involve: Noop
$ ./infrakit group commit oneview.json
Committed oneview: Noop
```

The --pretend appears to change the internal state to "committed" resulting in actual changes not being performed afterwards.

**Comment by wfarner** [comment]
Thanks for reporting!  I'm able to repro from the tutorial as well:

```console
$ build/infrakit group commit docs/cattle.json --pretend
Committing cattle would involve: Managing 5 instances
$ build/infrakit group commit docs/cattle.json --pretend
Committing cattle would involve: Noop
```
