### ISSUE TITLE
Make infrakit plugins available as Docker containers

### ISSUE THREAD

**Issue by chungers** [docker/infrakit#328]
Now that we hit v0.1.0, let's make InfraKit binaries available as Docker containers.   These can be released and tagged in lock-step to our release versions/ milestones.

The following needs to be done:

  + Dockerfile
  + Update / add documentation on how to run infrakit plugins as Docker containers

Using Docker containers will impact the implementation of #284 and more significantly how we reference plugins in the config JSONs.   A simple JSON field of `"Plugin": "infrakit-instance-vagrant"` won't have enough information about *how* to start the plugin a container (e.g. what's the image name, what flags?).   The activation implementation will have to take all this into account.

**Comment by thebsdbox** [comment]
I'm presuming the mechanism for using Docker containers would be for all docker InfraKit containers to share a mounted volume to allow the UNIX sockets to be accessed?

**Comment by chungers** [comment]
@thebsdbox  - yes.  The plugin-to-plugin communication remains the same with unix sockets.   Discovery mechanism still works the same.   Plugins as Docker containers should have clean shutdown which hopefully will alleviate the dangling socket files issue.  This seems to work well in my tests but I will test more before submitting a PR.
