### ISSUE TITLE
combo flavor plugin with terraform instance seems broken

### ISSUE THREAD

**Issue by linsun** [docker/infrakit#330]
I could not get my group.json for the swarm node work.  The main issue is that I don't see instance-*.json generated in the dir that I passed in when launching the build/infrakit-instance-terraform --dir=$dir cmd.    This used to work for me.  No log is generated in the build/infrakit-instance-terraform --dir=$dir cmd window other than "INFO[0000] Listening at: /Users/linsun/.infrakit/plugins/instance-terraform ".

My group.json is like:

{
  "ID": "terraform_demo_swarm_worker_sl",
  "Properties": {
    "Allocation": {
      "Size": 1
    },
    "Instance": {
      "Plugin": "instance-terraform",
      "Properties": {
        "type": "softlayer_virtual_guest",
        "value": {
          "cores": 2,
          "memory": 2048,
          "tags": [
            "terraform_demo_swarm_worker_sl"
          ],
          "connection": {
            "user": "root",
            "private_key": "${file(\"~/.ssh/id_rsa_de\")}"
          },
          "hourly_billing": true,
          "local_disk": true,
          "network_speed": 100,
          "datacenter": "dal10",
          "os_reference_code": "UBUNTU_14_64",
          "domain": "softlayer.com",
          "ssh_key_ids": [
            "${data.softlayer_ssh_key.public_key.id}"
          ],
          "post_install_script_uri": "https://sl-userdata.mybluemix.net/execute-userdata.sh"
        }
      }
    },
    "Flavor": {
      "Plugin": "flavor-combo",
      "Properties": {
        "Flavors": [
          {
            "Plugin": "flavor-vanilla",
            "Properties": {
              "Init": [
                "apt-get update -y",
                "apt-get upgrade -y",
                "wget -qO- https://get.docker.com/ | sh",
                "docker swarm init --advertise-addr $(ifconfig eth1 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'):4243",
                "echo DOCKER_OPTS=\"$DOCKER_OPTS -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock\" \u003e\u003e /etc/default/docker",
                "service docker restart"
              ]
            }
          },
          {
            "Plugin": "flavor-swarm",
            "Properties": {
              "Type": "worker",
              "DockerRestartCommand": "service docker restart"
            }
          }
        ]
      }
    }
  }

If I remove this section below, I can see the instance-*.json file generated thus the instance can be provisioned.

          {
            "Plugin": "flavor-swarm",
            "Properties": {
              "Type": "worker",
              "DockerRestartCommand": "service docker restart"
            }

I will investigate this more.

**Comment by linsun** [comment]
@chungers sorry for the delay on investigating this.  I have enabled the log level 5 for the terraform plugin... i don't see the terraform instance plugin provision get called if i'm reading correctly.  Essentially, i don't see the tf.json file generated, which is needed for terraform apply to work.  And i only see this prob when I use combo and flavor-swarm.

→ build/infrakit-instance-terraform --dir=/Users/linsun/go/src/github.ibm.com/ibmcloud/docker-for-bluemix/terraform-examples/swarm-cluster/swarm-worker --log=5
DEBU[0000] terraform instance plugin. dir= /Users/linsun/go/src/github.ibm.com/ibmcloud/docker-for-bluemix/terraform-examples/swarm-cluster/swarm-worker 
INFO[0000] Listening at: /Users/linsun/.infrakit/plugins/instance-terraform 
DEBU[1174] Received request POST / HTTP/1.1
Host: a
Accept-Encoding: gzip
Content-Length: 83
Content-Type: application/json
User-Agent: Go-http-client/1.1

{"jsonrpc":"2.0","method":"Plugin.Implements","params":{},"id":5939519119602725413} 
DEBU[1174] Sending response HTTP/1.1 200 OK
Connection: close
Content-Type: application/json; charset=utf-8
X-Content-Type-Options: nosniff

{"jsonrpc":"2.0","result":{"APIs":[{"Name":"Instance","Version":"0.1.0"}]},"id":5939519119602725413}
 
DEBU[1174] Received request POST / HTTP/1.1
Host: a
Accept-Encoding: gzip
Content-Length: 561
Content-Type: application/json
User-Agent: Go-http-client/1.1

{"jsonrpc":"2.0","method":"Instance.Validate","params":{"Properties":{"type":"softlayer_virtual_guest","value":{"cores":2,"memory":2048,"tags":["terraform_demo_swarm_worker_sl"],"connection":{"user":"root","private_key":"${file(\"~/.ssh/id_rsa_de\")}"},"hourly_billing":true,"local_disk":true,"network_speed":100,"datacenter":"dal10","os_reference_code":"UBUNTU_14_64","domain":"softlayer.com","ssh_key_ids":["${data.softlayer_ssh_key.public_key.id}"],"post_install_script_uri":"https://sl-userdata.mybluemix.net/execute-userdata.sh"}}},"id":544496995271456230} 
DEBU[1174] validate {"type":"softlayer_virtual_guest","value":{"cores":2,"memory":2048,"tags":["terraform_demo_swarm_worker_sl"],"connection":{"user":"root","private_key":"${file(\"~/.ssh/id_rsa_de\")}"},"hourly_billing":true,"local_disk":true,"network_speed":100,"datacenter":"dal10","os_reference_code":"UBUNTU_14_64","domain":"softlayer.com","ssh_key_ids":["${data.softlayer_ssh_key.public_key.id}"],"post_install_script_uri":"https://sl-userdata.mybluemix.net/execute-userdata.sh"}} 
DEBU[1174] Sending response HTTP/1.1 200 OK
Connection: close
Content-Type: application/json; charset=utf-8
X-Content-Type-Options: nosniff

{"jsonrpc":"2.0","result":{"OK":true},"id":544496995271456230}
 
DEBU[1174] Received request POST / HTTP/1.1
Host: a
Accept-Encoding: gzip
Content-Length: 150
Content-Type: application/json
User-Agent: Go-http-client/1.1

{"jsonrpc":"2.0","method":"Instance.DescribeInstances","params":{"Tags":{"infrakit.group":"terraform_demo_swarm_worker_sl"}},"id":2546557523476970066} 
DEBU[1174] describe-instances map[infrakit.group:terraform_demo_swarm_worker_sl] 
DEBU[1174] describe-instances result= []                
DEBU[1174] Sending response HTTP/1.1 200 OK
Connection: close
Content-Type: application/json; charset=utf-8
X-Content-Type-Options: nosniff

{"jsonrpc":"2.0","result":{"Descriptions":[]},"id":2546557523476970066}
 
DEBU[1184] Received request POST / HTTP/1.1
Host: a
Accept-Encoding: gzip
Content-Length: 150
Content-Type: application/json
User-Agent: Go-http-client/1.1

{"jsonrpc":"2.0","method":"Instance.DescribeInstances","params":{"Tags":{"infrakit.group":"terraform_demo_swarm_worker_sl"}},"id":1767040668839464875} 
DEBU[1184] describe-instances map[infrakit.group:terraform_demo_swarm_worker_sl] 
DEBU[1184] describe-instances result= []                
DEBU[1184] Sending response HTTP/1.1 200 OK
Connection: close
Content-Type: application/json; charset=utf-8
X-Content-Type-Options: nosniff

{"jsonrpc":"2.0","result":{"Descriptions":[]},"id":1767040668839464875}
 
DEBU[1190] Received request POST / HTTP/1.1
Host: a
Accept-Encoding: gzip
Content-Length: 150
Content-Type: application/json
User-Agent: Go-http-client/1.1

{"jsonrpc":"2.0","method":"Instance.DescribeInstances","params":{"Tags":{"infrakit.group":"terraform_demo_swarm_worker_sl"}},"id":6991615294428622444} 
DEBU[1190] describe-instances map[infrakit.group:terraform_demo_swarm_worker_sl] 
DEBU[1190] describe-instances result= []                
DEBU[1190] Sending response HTTP/1.1 200 OK
Connection: close
Content-Type: application/json; charset=utf-8
X-Content-Type-Options: nosniff

{"jsonrpc":"2.0","result":{"Descriptions":[]},"id":6991615294428622444}

**Comment by ndegory** [comment]
@linsun I think it fails because the Swarm plugin is expecting to have logical IDs for the instances. Using pet servers (with the `Size` allocation) does not generate logical IDs, so the flavor plugin fails to prepare, and the instance is not created.
I've been able to make it work on AWS with a patch on the Terraform instance plugin, which uses the logical IDs to set the private IP of the instance. It won't work on DigitalOcean, and I'm not sure how it will work on other providers.

**Comment by linsun** [comment]
@ndegory sorry i had forgot to update this, with @chungers's help, I got it working after moving to latest docker and infrakit code base.

**Comment by linsun** [comment]
I didn't use logical ID, but I did pass in the mgr ip and port when launching the swarm flavor plugin

**Comment by ndegory** [comment]
I see, it works if you already have a Swarm manager and you run infrakit in same network, thank you for the update. Still some issues if we try to setup a full Swarm cluster.
