### ISSUE TITLE
RPC Server Reflector prohibits plugin alternatives to Group

### ISSUE THREAD

**Issue by tristanls** [docker/infrakit#389]
I was surprised that InfraKit supports top-level plugins (alternatives to Group) only from Docker. This was surprising due to the advertised "plugin" nature of the project.

This particular line is prohibitive: 
[`if !strings.Contains(t.PkgPath(), "github.com/docker/infrakit/pkg/rpc") {`](https://github.com/docker/infrakit/blob/908e9fb6762dd5d4c12c705b10973142f60d3e7b/pkg/rpc/server/reflector.go#L47-L53)

Any reason for this? 

Commenting it out in my patched vendored version of InfraKit allows me to start my plugin successfully.

**Comment by chungers** [comment]
@tristanls - thanks for this feedback.   I didn't know that there are other projects that are working on alternatives to the Group plugin.  This check was added simply as a safety.   It can be removed.  Sounds to me that you are able to run your implementation without any problems?   If so, would you mind send a PR with the check removed and I will merge it in?

Also, let me know if you run into any issues using the rpc package in your Golang project.  The packages are designed to be reused wherever possible, so if you find any api / library issues please let me know.  Thanks!
