### ISSUE TITLE
Shared volume challenges with a bootstrap VM and the initial leader manager

### ISSUE THREAD

**Issue by kaufers** [docker/infrakit#556]
We are provisioning a swarm using a bootstrap VM; the purpose of this VM is to create the initial manager that will then scale out the swarm to the desired number of managers and workers.

Note that we are using the bootstrap VM (vs. simply having this VM _be_ the initial manager) because of issues getting the terraform state for this VM (see https://github.com/docker/infrakit/issues/533).

The boostrap VM is running the group plugin in `os` mode and commits a mangers group with a single instance; the terraform state file and the associated `.tf.json` are in a shared NFS volume with the manager being provisioned.

Once the manager is provisioned, we need to be careful with the changes to the `.tf.json` files and to the terraform state file since there will be 2 sets of Infrakit plugins running (1 on the bootstrap VM and 1 on the initial manger) that share these files.

First, the bootstrap VM needs to stop monitoring the managers group; if it does not, then any `.tf.json` files that are laid down for the second and third managers will be detected and attempted to be deleted. Simply doing a `free` after a successful `commit` on the managers group solves this problem.

Second, the instance plugin needs to stop calling `terraform apply` (which is does at most every 10 seconds).  When the initial manager commits it's managers group, new `.tf.json` files are laid down and we do not want the bootstrap node to process them. Note that there is a lock file but it's possible that the bootstrap VM gets the lock and does the `terraform apply` -- if the bootstrap VM is destroyed while holding the lock we could get into a bad state.

How can we disable the terraform polling on the bootstrap VM? In this scenario there is no SSH access between the VMs -- we only have the the shared NFS.  Could we put down a file that would disable the polling? If so, we'd probably want a new CLI option on the instance-plugin so that this feature is opt-in.

Thoughts @chungers?

**Comment by kaufers** [comment]
This seems to be related to https://github.com/docker/infrakit/issues/268. What @linsun described is what I'm seeing as well; specifically:

1. Issue a group `commit` -- this starts the terraform polling
2. Issue a group `free` so that there are no more groups -- the terraform polling is still running

Also, if you restart the instance plugin that automatically kills the polling; this seems like it could be problematic.  Polling is only re-started when the instance plugin's `Provision`, `Label`, or `Destroy` functions are invoked.

Why not simply poll *only* if there are groups being managed? This would solve the problem in this issue (since a `free` would disable polling) and then add some resiliency if the instance plugin was restarted (since the polling would continue on restart if there were groups).

**Comment by lab616** [comment]
We could implement the file-based leader detection into the terraform plugin so that a tf plugin runs tf apply if and only if it is a "leader":  https://github.com/docker/infrakit/blob/master/cmd/manager/os.go#L75

This way we just place a file that names the active plugin. By changing the name in this file, we control which instance does the polling at any given time.  We could even use the same leader file that the manager replicas share and in doing so control the active manager and tf plugin with a change to a single file and there's no need to call free.   

Thoughts?

**Comment by kaufers** [comment]
Summary after talking with @chungers in Slack:

1. Bootstrap VM should *not* free the managers group; instead the existing support to re-define the leader by updating the `/infrakit/leader` file will be utilized. When the initial manager is successfully booted, it will update that file so that the group plugin on the bootstrap VM goes into standby mode; this means that it will no longer monitor the group.
2. Add support to expose metadata when the leadership changes.
3. Add support to the instance plugin to subscribe to the data exposed in 2; when it detects that leadership has changed it will stop polling.

**Comment by kaufers** [comment]
Another use case to consider: when the leader manager changes we need to ensure that the terraform polling is running on that new leader (and disabled on the previous leader).

Today, the initial manager (which later became a standby) still had the polling enabled and the current leader did not.

**Comment by chungers** [comment]
In an earlier conversation I talked about using the events API to communicate leadership changes from the manager to the terraform plugin so that we can put the terraform plugin on standby mode.  There's also a rpc method on the manager to poll for the leadership state.  

I think the easiest and most reliable solution is to add a small polling loop in the terraform plugin calling the manager rpc method for leadership status.   Events sounds like a good idea but without ordering and guaranteed delivery it's not going to be as reliable as good honest polling.

I will put together a PR for this.  Wdyt?

**Comment by kaufers** [comment]
@chungers Sure, this sounds good. Once this is done then we should only have 1 terraform plugin running `terraform apply`, right?

If so, then can we make this more robust? https://github.com/docker/infrakit/blob/master/examples/instance/terraform/apply.go#L32

The motivation for current random sleep time was to prevent multiple managers from colliding (since they would all be running `apply`). Can we make this more predictable and have it poll at a configured frequency?  Maybe default to 30 seconds and have a CLI to override?  This can be outside the scope of this issue but I wanted to run the idea by you.

**Comment by chungers** [comment]
@kaufers  - I think that's reasonable.  And if the flag is not set we just revert to current behavior?  Would you mind sending a PR?

**Comment by kaufers** [comment]
@chungers will do, thanks!

**Comment by kaufers** [comment]
@chungers see PR https://github.com/docker/infrakit/pull/596 for CLI polling updates
