### ISSUE TITLE
Remote access must require auth

### ISSUE THREAD

**Issue by chungers** [docker/infrakit#557]
Currently the mux proxy that supports remote CLI access does not require any authentication and does not encrypt the messages during transport.  This must be fixed.

Considerations:
     
1 Use simple HTTP password auth.  This is easy to implement (as auth info are in the headers), but introduces the problem of password management.
 
2 Use OAuth.  We can incorporate a server side handler that can handle the OAuth flow.  There are some complexities around this:
  + OAuth set up with Google or Github requires an app id... this is hard to create and register for a swarm / cluster of infrakit-managed nodes. 
  + Using https would require self-signed certs unless one is provided for a registered domain.  This again creates challenges for an ad-hoc cluster created by infrakit.
  
3 Use a third-party identity provider like auth0 or okta.  These require api integration and eventually require paid services
  
4 Implement a basic LDAP plugin?

@YujiOshima @ndegory  - what are your thoughts?  Any specific requirements on how you'd manage auth in your environment?

**Comment by justincormack** [comment]
Or use SSH. People already have keys. There is a PR for Moby/moby to
support this.

**Comment by YujiOshima** [comment]
Is that you want to manage per user?
In my understanding, it will to manage users and restrict resources (plugins, clusters, events) that users can operate?
In my opinion, HTTP password authentication is OK for the first step.
HTTP authentication is easy not only to implement but also to test using.
Password management is certainly a problem. If you do same way with instance plugins, it will be made persistent by writing to the file. 
Will you introduce DB plugin?
Also, the LDAP plugin is very useful. Since we already use LDAP with many services, it is easy to cooperate with other our existing services.
And not so difficult to implement.
OAuth is good for public service but implementation would be complex.

@justincormack
Yeah, it's so developer friendly. We must manage the keys same as HTTP authentication.

Default is use HTTP password and then make LDAP, OAuth, SSH, etc. plugin, WDYT?

**Comment by ndegory** [comment]
I agree, we absolutely need a basic authentication layer on the mux server.
My current use case is deploying 3 swarm managers with infrakit running on each node to take care of the worker groups.
Out of the box, once the InfraKit service is up I should be able to remotely push the InfraKit configuration in a secure enough way. Basic http authentication would be enough. I was thinking adding an nginx container in front of InfraKit to do that job, but if it's already implemented in InfraKit, that would simplify the deployment.
Then for a better implementation we can add TLS support for mutual auth (Cf. the engine API), but that shouldn't be required by default.

**Comment by chungers** [comment]
@justincormack @YujiOshima 

I will take a look at the SSH implementation since that may be a better alternative than HTTP password auth.  After that I think we can do a LDAP plugin to support Yuji's use case right away.  OAuth is tricky because the clusters come and go and as a result it's hard to have a fixed domain/ app id for OAuth's flow to work properly.  

Coincidentally - the SSH PR https://github.com/moby/moby/pull/32161 is by @AkihiroSuda so the SSH approach should work for yuji as well since you're in the same org?

**Comment by chungers** [comment]
@ndegory - will the SSH approach work for you?  this will be built into the mux itself, with the goal being to simplify deployment.

**Comment by chungers** [comment]
The SSH approach already works today, even if it's a two step process:

1. This assumes the port 24864 on the remote hosts are open for traffic on the hosts but not outside the firewall.
2. Locally just start a SSH tunnel: `ssh -L localhost:9999:localhost:24864 user@remote_ip`  This starts up SSH and leave it running.
3. Add the localhost and port via `infrakit remote add myremote1 localhost:9999` using example above.
4. Point to the remote via `export INFRAKIT_HOST=myremote1`
5. Now `infrakit plugin ls` will list the plugins on the remote host, etc.  

You can use multiple `-L` options and add the localhost:port as a list when calling `infrakit remote add`.  The CLI will check for the leader in that list and make calls to the leader directly.

This looks like the gist of the moby/moby PR, other than that it shells out to ssh on unix and it uses the streamlocal  option to forward traffic on local socket to socket on remote host.

I will look at implementing the shelling out to ssh.  After that I will look at adding real auth plugin so we can integrate with LDAP.
