### ISSUE TITLE
Issue parsing `infrakit-link-create` tags for terraform Softlayer instances

### ISSUE THREAD

**Issue by kaufers** [docker/infrakit#570]
In Softlayer, all tags must be lower case. This causes a problem for the `infrakit-link-create`, which is has a value like:

```
2017-05-25T19:41:07Z
```

This tag value is changed to the following:

```
2017-05-25t19:41:07z
```

This case of the `t` and `z` cause issues when parsing via `time.Parse(time.RFC3339, <timeString>)`
```	
	Error:		Received unexpected error:
			parsing time "2017-05-25t20:03:51z" as "2006-01-02T15:04:05Z07:00": cannot parse "t20:03:51z" as "T"
```

Is there any reason why we can't `ToUpper` this code: 
 https://github.com/docker/infrakit/blob/master/pkg/types/link.go#L54

**Comment by chungers** [comment]
I think that's fine.  We should add some validation / conversion to account for that case.  Send a PR?

**Comment by kaufers** [comment]
Will do, thanks @chungers!
