### ISSUE TITLE
instance-vsphere should support additional properties

### ISSUE THREAD

**Issue by stealthybox** [docker/infrakit#620]
@thebsdbox

`Datastore`, `Cluster`, and `ResourcePool` should be selectable for instance placement.
It seems not all environments have configured defaults for these fields.

As an example, my group is similar to #618 and fails to deploy, because multiple datacenters are available:
```
INFO[4147] Adding 1 instances to group to reach desired 1
ERRO[0519] Error:
No Datacenter instance could be found inside of vCenter default datacenter resolves to multiple instances, please specify
ERRO[4147] Failed to provision: No Datacenter instance could be found inside of vCenter default datacenter resolves to multiple instances, please specify
INFO[4150] Ignored group 'Infrakit_Deployment'
WARN[0522] No Instances found
```

Asking the user to specify these values is probably the simplest solution.

@bdeluca also had some interesting requests around round-robining across enums when multiple are available which could potentially be a separate feature.

_________________________
**Plugin:** instance-vsphere / flavor-vanilla / group-default
**Infrakit Commit:** c8080c959594a0d28d521d3ddd9f29036a373489
**vSphere Version:** 6.5

**Comment by thebsdbox** [comment]
Added the capabilities in #624 

There has been additional capabilities added since, which the scripting engine will consume.
