### ISSUE TITLE
User data script for initial manager VM

### ISSUE THREAD

**Issue by kaufers** [docker/infrakit#645]
The user data script that executes on the initial manager VM is **not generated via Infrakit** and has specific bootstrapping commands; this works great for the initial manager but the following flow causes issues:

1. Provision the initial manager outside of Infrakit; create boot script in the user data 
2. Import the initial manager into terraform and then create the rest of the swarm (2 more managers and _n_ workers).
3. Delete the initial manager node from the cloud provider; forcing a standby node to assume leadership
4. `terraform apply` (running on the new leader manger node) re-creates a manager node using the data in the existing `.tf.json` file that was generated when the initial manager was imported

In this flow, when the manager node is recovered, it runs the same script that created the swarm. Instead of this script, it needs to run an **Infrakit-generated** script that is used on all of the other standby nodes (for example, it needs the `SWARM_JOIN_TOKENS.Manager` value for the swarm).

Also, how will it get the IP of a manger node to use? Using the 10.x of the initial manager works for all other nodes (since the initial manager will eventually bind back to the same private IP) but it will not work for the node that replaces the initial manager.

Once the swarm is created, can we use Infrakit to generate an updated userdata script for the initial manager node? This would only be invoked on node recovery.

Any other thoughts on how to handle this?

**Comment by chungers** [comment]
I am a little confused...  when the original manager node is terminated (outside of infrakit's control), one of the followers will become the leader, and the infrakit plugins running on that node will run according to the shared spec.  When the new node is started, wouldn't that be created with the same userdata section as every other node (as you called *infrakit-generated* script)?

**Comment by kaufers** [comment]
When the new node assumes leadership nothing is regenerated; the `.tf.json` file that is associated with the initial manager (which was imported) has the non-infrakit generated user data script. Terraform detects that this node is no longer in the cloud and re-creates it according to the spec in the `.tf.json` file.

**Comment by kaufers** [comment]
After talking with @chungers, we determined that this problem is isolated to the terraform plugin; the way that we are using terraform currently does not allow us to detect if a resource has been removed out-of-band.

The fix is to do something like the following before a `terrafrom apply`:
1. Execute a `terraform refresh` to update terraform's state file
2. Execute a `terraform state list` to retrieve the list of all resource types and IDs
3. Check the `tf.json` files to determine if any are not in the state and, if so, remove the orphaned `.tf.json` file

This will prevent the `terraform apply` goroutine from re-creating the resource using an **old instance definition**. Once the file has been removed, then the group controller will issue `DescribeInstances` RPC calls, detect that a group member is missing, and then issue a `Provision` with an **updated instance spec**.

Note: Steps 1-3 work great for finding orphaned `.tf.json` files that **should be removed**; however, it will **prevent new instances** from ever being provisioned (not ideal). We need to modify the file names so that we can flag files that should not be in the state and allow them to be created.

**Comment by kaufers** [comment]
Here's the new design that should address this:

On `Provision`, the file created has a `tf.json.new` suffix (not that `terraform apply` will ignore these files but the Instance's Destroy/Describe/Label functions will **not**). The `apply` goroutine will be changed to execute:

1. Acquire file lock
2. `terraform refresh`
3. Detect orphan `tf.json` files (corresponding to resources that are not in the terraform state file) by running `terraform state list` and delete
4. Rename `tf.json.new` files to `tf.json` so that terraform will create them
5. Release file lock
6. `terraform apply`

This allows us to determine which `tf.json` files are orphaned.
