### ISSUE TITLE
Add task for swarm join in provision workflow

### ISSUE THREAD

**Issue by chungers** [docker/infrakit#71]
Currently in the Editions / 1.12 TP2 the behavior of a node when provisioned is that it automatically joins the cluster via 
```
docker swarm join <master_ip>:4500
```
which is executed via the user data for the instance when the Moby instance comes up (as part of an autoscaling group).

For other environments where autoscaling is absent (pretty much everyone else outside of AWS, Azure, GCE), machete needs to run the cluster join as a task in the provisioning workflow.

Assumptions:
  + Same cluster (no provision and join arbitrary swarms)
  + Configuration / manager IP address would have to be passed in as a configuration parameter in the machine template.  Editions or some other client can generate / update the machine template once the Swarm manager IP is known.

**Comment by wfarner** [comment]
Closing this as InfraKit has evolved quite a bit since the discussion began.  Swarm-related behavior will now be delegated to a plugin, which currently does support join behavior.
