### ISSUE TITLE
Handle Load Balancers which don't support specific protocols

### ISSUE THREAD

**Issue by ericvn** [docker/infrakit#788]
We are seeing an issue where the protocols specified in the _Publish_ call are not supported on a given load balancer. This results in some cycling of Routes (see below) and this issue is to determine the best way forward.

If we try and map the protocols to ones that are supported on the load balancer, we have an issue with what to do in the _Routes_ call. If we return the mapped values back to InfraKit, it will detect a change and try and remove the load balancer and add a new one. This results in cycling of routes. If we try and map the values back in the _Routes_ call, it fixes this issue in this one case.  However, if the user would use the correct protocols in a CLI call, they would get incorrectly mapped back and InfraKit would cycle the Routes again.

We could try and determine a way to persist that we did a mapping in the _Publish_ call and use that to determine whether we map back in the _Routes_ call. Is this the correct way to handle this?

Another option, which I'm fine creating a PR for if it makes sense, would be to provide an _IGNORE_ ?protocol option which could be used in the _Routes_ call to signify back to InfraKit that it should ignore the field when it's doing it logic to verify if a Route is invalid. This would only be used for instances where mapping might have taken place.

**Comment by chungers** [comment]
Can you give me an example of this?  What's the protocol that is supported by the L4 lb that isn't supported by the ingress controller?

**Comment by chungers** [comment]
This issue has been addressed by #790. Closing.
