### ISSUE TITLE
Systematic logging support

### ISSUE THREAD

**Issue by chungers** [docker/infrakit#83]
Right now logging is pretty ad-hoc.  Other than using logrus here and there, there is no pattern or systematic support for provisioner developers.  `docker-machine` exposes logger for driver developers to use and libmachete should as well.

**Comment by linsun** [comment]
We really need to enhance the logging support.  First of all, all logging should have timestamp.  2nd, the current code has little or no log, it is really hard to debug things when stuff goes wrong.

**Comment by wfarner** [comment]
@linsun completely agreed that logging is too sparse right now.  This issue relates to a logging framework for use in plugins, so i've filed #269 to track improvements to the thoroughness of logging.

**Comment by chungers** [comment]
#440 implements this
