### ISSUE TITLE
Renaming this project

### ISSUE THREAD

**Issue by justincormack** [docker/infrakit#919]
Unfortunately we have been notified that another entity owns a trademark on the "infrakit" name, and it probably makes sense to choose a new name for this project. Suggestions welcome...

**Comment by thaJeztah** [comment]
Need to update https://en.wikipedia.org/wiki/InfraKit as well (first result hit for me)

**Comment by thebsdbox** [comment]
I was thinking of something along the lines of:

- `DeployKit`
- `MachineKit`
- `InfrastructureKit`

**Comment by th31nitiate** [comment]
Is this project still alive thought or is it gone at this stage?

**Comment by justincormack** [comment]
`Deploykit` sounds good to me.

**Comment by justincormack** [comment]
@th31nitiate no one is currently working on this as you can see from the commits...

**Comment by justincormack** [comment]
renamed.
